export default {
    INIT_AUTH_DATA: "INIT-AUTH-DATA",
    INIT_CARDS: "INIT_ALL_CARDS",
    ADD_CARD: "ADD_CARD",
    INIT_CHAT: "INIT_CHAT",
    ADD_MESSAGE: "ADD_MESSAGE",
    CLEAR_CHAT: "CLEAR_CHAT",
    DELETE_CARD: "DELETE_CARD"
}